# Generated by Django 5.0.6 on 2024-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_id', models.IntegerField(max_length=250)),
                ('Book_name', models.CharField(max_length=250)),
                ('Borr_id', models.IntegerField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Phone', models.IntegerField(max_length=250)),
            ],
        ),
    ]
